generalConfig:
  # minutes
  simulationTime:
    - 30
  # minutes
  warmUpPeriod:
    - 3
  vmLoadCheckInterval:
    - 0.1
  locationCheckInterval:
    - 0.1
  fileLogEnabled: true
  deepFileLogEnabled: false
  minNumberOfMobileDevices: 100
  maxNumberOfMobileDevices: 500
  mobileDeviceCounterSize: 10
  # sec
  wanPropagationDelay:
    - 0.15
  gsmPropagationDelay:
    - 0.16
  lanInternalDelay:
    - 0.01
  #Mbps
  wlanBandwidth:
    - 200
  wanBandwidth:
    - 15
  gsmBandwidth:
    - 10
  numberOfHostOnCloudDatacenter:
    - 1
  numberOfVmOnCloudHost:
    - 1
  coreForCloudVm:
    - 128
  mipsForCloudVm:
    - 120000
  ramForCloudVm:
    - 128000
  storageForCloudVm:
    - 1000000
  coreForMobileVm:
    - 1
  mipsForMobileVm:
    - 1000
  ramForMobileVm:
    - 1800
  storageForMobileVm:
    - 32000
  # RANDOM_FIT, FIRST_FIT, NEXT_FIT, WORST_FIT, BEST_FIT, ONLY_EDGE
  orchestratorPolicies: NEXT_FIT
  simulationScenarios: SINGLE_TIER,TWO_TIER,TWO_TIER_WITH_EO
  # sec
  attractivenessL1MeanWaitingTime:
    - 600
  # sec
  attractivenessL2MeanWaitingTime:
    - 120
  # sec
  attractivenessL3MeanWaitingTime:
    - 60
edgesConfig:
  costPerBw: 0.1
  costPerSec: 3.0
  costPerMem: 0.05
  costPerStorage: 0.1
  edgeCount: 1
  edgeCore: 16
  edgeMips: 12000
  edgeRam: 16000
  edgeStorage: 250000
  edgeVwCount: 1
  locations:
    - x: 1
      y: 1
      attractiveness: 2 # 0, 1, 2
    - x: 1
      y: 2
      attractiveness: 1 # 0, 1, 2
    - x: 1
      y: 3
      attractiveness: 2 # 0, 1, 2
    - x: 2
      y: 1
      attractiveness: 1 # 0, 1, 2
    - x: 2
      y: 2
      attractiveness: 0 # 0, 1, 2
    - x: 2
      y: 3
      attractiveness: 1 # 0, 1, 2
    - x: 3
      y: 1
      attractiveness: 2 # 0, 1, 2
    - x: 3
      y: 2
      attractiveness: 1 # 0, 1, 2
    - x: 3
      y: 3
      attractiveness: 2 # 0, 1, 2
inputDeployConfig:
  sensingUploadData: 0.5
  actuatorDownloadData: 1.0
  behaviour:
    name: "behaviour"
    probCloudSelection: [ 0.0, 25.0, 50.0, 75.0, 100.0 ]
    poissonInterarrival: [5.0]
    activePeriod: [20.0] # sec
    idlePeriod: [0.0] # sec
    vmUtilizationOnEdge: [25.0]
    vmUtilizationOnCloud: [4.0]
    vmUtilizationOnMobile: [0.0]
  communication:
    name: "communication"
    probCloudSelection: [ 0.0, 25.0, 50.0, 75.0, 100.0 ]
    poissonInterarrival: [ 5.0 ]
    activePeriod: [ 20.0 ]
    idlePeriod: [ 0.0 ]
    taskLength: [ 15.0 ]
    vmUtilizationOnEdge: [ 25.0 ]
    vmUtilizationOnCloud: [ 4.0 ]
    vmUtilizationOnMobile: [ 0.0 ]